# Simple CD

name: push_cd

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun i
      - name: Build production bundle
        run: bun run build --outDir ${{secrets.OUT_DIR}}
      - name: Fix perms for nginx
        run: chmod -R 755 ${{secrets.OUT_DIR}}
